"""
Converts one or more sample_request.json files (from fetch_data.py) into a
single TypeScript file with a PRESET_ASSETS constant, ready to paste into
AssetForm.tsx.

Usage:
    python generate_preset_assets.py sample_request.json
    python generate_preset_assets.py aapl_googl_msft.json aapl_jnj_xom_tlt.json
"""

import json
import sys


def generate_typescript(json_files: list[str], output_path: str = "preset_assets.ts"):
    merged_assets: dict[str, list[float]] = {}

    for file_path in json_files:
        with open(file_path, "r") as f:
            data = json.load(f)

        for asset in data["assets"]:
            name = asset["name"]
            merged_assets[name] = asset["historical_returns"]

    lines = [
        "// AUTO-GENERATED by generate_preset_assets.py — do not hand-edit",
        "// Paste this into src/components/AssetForm.tsx, replacing the",
        "// existing PRESET_ASSETS constant.",
        "",
        "export const PRESET_ASSETS: Record<string, number[]> = {",
    ]

    for name, returns in merged_assets.items():
        values_str = ",".join(str(r) for r in returns)
        lines.append(f"  {name}: [{values_str}],")

    lines.append("};")

    output = "\n".join(lines)

    with open(output_path, "w") as f:
        f.write(output)

    print(f"Wrote {len(merged_assets)} assets to {output_path}")
    print(f"Assets included: {', '.join(merged_assets.keys())}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_preset_assets.py <sample_request.json> [more_files...]")
        sys.exit(1)

    generate_typescript(sys.argv[1:])